# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/c/Program Files (x86)/CMake 2.8/bin/cmake.exe"

# The command to remove a file.
RM = "/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/c/Program Files (x86)/CMake 2.8/bin/cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/cproject/irrtest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/cproject/irrtest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/cproject/irrtest/CMakeFiles /C/cproject/irrtest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/cproject/irrtest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named metoritewars

# Build rule for target.
metoritewars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metoritewars
.PHONY : metoritewars

# fast build rule for target.
metoritewars/fast:
	$(MAKE) -f CMakeFiles/metoritewars.dir/build.make CMakeFiles/metoritewars.dir/build
.PHONY : metoritewars/fast

src/Core/SPK_BufferHandler.obj: src/Core/SPK_BufferHandler.cpp.obj
.PHONY : src/Core/SPK_BufferHandler.obj

# target to build an object file
src/Core/SPK_BufferHandler.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_BufferHandler.cpp.obj
.PHONY : src/Core/SPK_BufferHandler.cpp.obj

src/Core/SPK_BufferHandler.i: src/Core/SPK_BufferHandler.cpp.i
.PHONY : src/Core/SPK_BufferHandler.i

# target to preprocess a source file
src/Core/SPK_BufferHandler.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_BufferHandler.cpp.i
.PHONY : src/Core/SPK_BufferHandler.cpp.i

src/Core/SPK_BufferHandler.s: src/Core/SPK_BufferHandler.cpp.s
.PHONY : src/Core/SPK_BufferHandler.s

# target to generate assembly for a file
src/Core/SPK_BufferHandler.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_BufferHandler.cpp.s
.PHONY : src/Core/SPK_BufferHandler.cpp.s

src/Core/SPK_DEF.obj: src/Core/SPK_DEF.cpp.obj
.PHONY : src/Core/SPK_DEF.obj

# target to build an object file
src/Core/SPK_DEF.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_DEF.cpp.obj
.PHONY : src/Core/SPK_DEF.cpp.obj

src/Core/SPK_DEF.i: src/Core/SPK_DEF.cpp.i
.PHONY : src/Core/SPK_DEF.i

# target to preprocess a source file
src/Core/SPK_DEF.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_DEF.cpp.i
.PHONY : src/Core/SPK_DEF.cpp.i

src/Core/SPK_DEF.s: src/Core/SPK_DEF.cpp.s
.PHONY : src/Core/SPK_DEF.s

# target to generate assembly for a file
src/Core/SPK_DEF.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_DEF.cpp.s
.PHONY : src/Core/SPK_DEF.cpp.s

src/Core/SPK_Emitter.obj: src/Core/SPK_Emitter.cpp.obj
.PHONY : src/Core/SPK_Emitter.obj

# target to build an object file
src/Core/SPK_Emitter.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Emitter.cpp.obj
.PHONY : src/Core/SPK_Emitter.cpp.obj

src/Core/SPK_Emitter.i: src/Core/SPK_Emitter.cpp.i
.PHONY : src/Core/SPK_Emitter.i

# target to preprocess a source file
src/Core/SPK_Emitter.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Emitter.cpp.i
.PHONY : src/Core/SPK_Emitter.cpp.i

src/Core/SPK_Emitter.s: src/Core/SPK_Emitter.cpp.s
.PHONY : src/Core/SPK_Emitter.s

# target to generate assembly for a file
src/Core/SPK_Emitter.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Emitter.cpp.s
.PHONY : src/Core/SPK_Emitter.cpp.s

src/Core/SPK_Factory.obj: src/Core/SPK_Factory.cpp.obj
.PHONY : src/Core/SPK_Factory.obj

# target to build an object file
src/Core/SPK_Factory.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Factory.cpp.obj
.PHONY : src/Core/SPK_Factory.cpp.obj

src/Core/SPK_Factory.i: src/Core/SPK_Factory.cpp.i
.PHONY : src/Core/SPK_Factory.i

# target to preprocess a source file
src/Core/SPK_Factory.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Factory.cpp.i
.PHONY : src/Core/SPK_Factory.cpp.i

src/Core/SPK_Factory.s: src/Core/SPK_Factory.cpp.s
.PHONY : src/Core/SPK_Factory.s

# target to generate assembly for a file
src/Core/SPK_Factory.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Factory.cpp.s
.PHONY : src/Core/SPK_Factory.cpp.s

src/Core/SPK_Group.obj: src/Core/SPK_Group.cpp.obj
.PHONY : src/Core/SPK_Group.obj

# target to build an object file
src/Core/SPK_Group.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Group.cpp.obj
.PHONY : src/Core/SPK_Group.cpp.obj

src/Core/SPK_Group.i: src/Core/SPK_Group.cpp.i
.PHONY : src/Core/SPK_Group.i

# target to preprocess a source file
src/Core/SPK_Group.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Group.cpp.i
.PHONY : src/Core/SPK_Group.cpp.i

src/Core/SPK_Group.s: src/Core/SPK_Group.cpp.s
.PHONY : src/Core/SPK_Group.s

# target to generate assembly for a file
src/Core/SPK_Group.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Group.cpp.s
.PHONY : src/Core/SPK_Group.cpp.s

src/Core/SPK_Interpolator.obj: src/Core/SPK_Interpolator.cpp.obj
.PHONY : src/Core/SPK_Interpolator.obj

# target to build an object file
src/Core/SPK_Interpolator.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Interpolator.cpp.obj
.PHONY : src/Core/SPK_Interpolator.cpp.obj

src/Core/SPK_Interpolator.i: src/Core/SPK_Interpolator.cpp.i
.PHONY : src/Core/SPK_Interpolator.i

# target to preprocess a source file
src/Core/SPK_Interpolator.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Interpolator.cpp.i
.PHONY : src/Core/SPK_Interpolator.cpp.i

src/Core/SPK_Interpolator.s: src/Core/SPK_Interpolator.cpp.s
.PHONY : src/Core/SPK_Interpolator.s

# target to generate assembly for a file
src/Core/SPK_Interpolator.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Interpolator.cpp.s
.PHONY : src/Core/SPK_Interpolator.cpp.s

src/Core/SPK_Model.obj: src/Core/SPK_Model.cpp.obj
.PHONY : src/Core/SPK_Model.obj

# target to build an object file
src/Core/SPK_Model.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Model.cpp.obj
.PHONY : src/Core/SPK_Model.cpp.obj

src/Core/SPK_Model.i: src/Core/SPK_Model.cpp.i
.PHONY : src/Core/SPK_Model.i

# target to preprocess a source file
src/Core/SPK_Model.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Model.cpp.i
.PHONY : src/Core/SPK_Model.cpp.i

src/Core/SPK_Model.s: src/Core/SPK_Model.cpp.s
.PHONY : src/Core/SPK_Model.s

# target to generate assembly for a file
src/Core/SPK_Model.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Model.cpp.s
.PHONY : src/Core/SPK_Model.cpp.s

src/Core/SPK_Modifier.obj: src/Core/SPK_Modifier.cpp.obj
.PHONY : src/Core/SPK_Modifier.obj

# target to build an object file
src/Core/SPK_Modifier.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Modifier.cpp.obj
.PHONY : src/Core/SPK_Modifier.cpp.obj

src/Core/SPK_Modifier.i: src/Core/SPK_Modifier.cpp.i
.PHONY : src/Core/SPK_Modifier.i

# target to preprocess a source file
src/Core/SPK_Modifier.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Modifier.cpp.i
.PHONY : src/Core/SPK_Modifier.cpp.i

src/Core/SPK_Modifier.s: src/Core/SPK_Modifier.cpp.s
.PHONY : src/Core/SPK_Modifier.s

# target to generate assembly for a file
src/Core/SPK_Modifier.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Modifier.cpp.s
.PHONY : src/Core/SPK_Modifier.cpp.s

src/Core/SPK_Particle.obj: src/Core/SPK_Particle.cpp.obj
.PHONY : src/Core/SPK_Particle.obj

# target to build an object file
src/Core/SPK_Particle.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Particle.cpp.obj
.PHONY : src/Core/SPK_Particle.cpp.obj

src/Core/SPK_Particle.i: src/Core/SPK_Particle.cpp.i
.PHONY : src/Core/SPK_Particle.i

# target to preprocess a source file
src/Core/SPK_Particle.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Particle.cpp.i
.PHONY : src/Core/SPK_Particle.cpp.i

src/Core/SPK_Particle.s: src/Core/SPK_Particle.cpp.s
.PHONY : src/Core/SPK_Particle.s

# target to generate assembly for a file
src/Core/SPK_Particle.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Particle.cpp.s
.PHONY : src/Core/SPK_Particle.cpp.s

src/Core/SPK_Registerable.obj: src/Core/SPK_Registerable.cpp.obj
.PHONY : src/Core/SPK_Registerable.obj

# target to build an object file
src/Core/SPK_Registerable.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Registerable.cpp.obj
.PHONY : src/Core/SPK_Registerable.cpp.obj

src/Core/SPK_Registerable.i: src/Core/SPK_Registerable.cpp.i
.PHONY : src/Core/SPK_Registerable.i

# target to preprocess a source file
src/Core/SPK_Registerable.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Registerable.cpp.i
.PHONY : src/Core/SPK_Registerable.cpp.i

src/Core/SPK_Registerable.s: src/Core/SPK_Registerable.cpp.s
.PHONY : src/Core/SPK_Registerable.s

# target to generate assembly for a file
src/Core/SPK_Registerable.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Registerable.cpp.s
.PHONY : src/Core/SPK_Registerable.cpp.s

src/Core/SPK_Renderer.obj: src/Core/SPK_Renderer.cpp.obj
.PHONY : src/Core/SPK_Renderer.obj

# target to build an object file
src/Core/SPK_Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Renderer.cpp.obj
.PHONY : src/Core/SPK_Renderer.cpp.obj

src/Core/SPK_Renderer.i: src/Core/SPK_Renderer.cpp.i
.PHONY : src/Core/SPK_Renderer.i

# target to preprocess a source file
src/Core/SPK_Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Renderer.cpp.i
.PHONY : src/Core/SPK_Renderer.cpp.i

src/Core/SPK_Renderer.s: src/Core/SPK_Renderer.cpp.s
.PHONY : src/Core/SPK_Renderer.s

# target to generate assembly for a file
src/Core/SPK_Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Renderer.cpp.s
.PHONY : src/Core/SPK_Renderer.cpp.s

src/Core/SPK_System.obj: src/Core/SPK_System.cpp.obj
.PHONY : src/Core/SPK_System.obj

# target to build an object file
src/Core/SPK_System.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_System.cpp.obj
.PHONY : src/Core/SPK_System.cpp.obj

src/Core/SPK_System.i: src/Core/SPK_System.cpp.i
.PHONY : src/Core/SPK_System.i

# target to preprocess a source file
src/Core/SPK_System.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_System.cpp.i
.PHONY : src/Core/SPK_System.cpp.i

src/Core/SPK_System.s: src/Core/SPK_System.cpp.s
.PHONY : src/Core/SPK_System.s

# target to generate assembly for a file
src/Core/SPK_System.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_System.cpp.s
.PHONY : src/Core/SPK_System.cpp.s

src/Core/SPK_Transformable.obj: src/Core/SPK_Transformable.cpp.obj
.PHONY : src/Core/SPK_Transformable.obj

# target to build an object file
src/Core/SPK_Transformable.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Transformable.cpp.obj
.PHONY : src/Core/SPK_Transformable.cpp.obj

src/Core/SPK_Transformable.i: src/Core/SPK_Transformable.cpp.i
.PHONY : src/Core/SPK_Transformable.i

# target to preprocess a source file
src/Core/SPK_Transformable.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Transformable.cpp.i
.PHONY : src/Core/SPK_Transformable.cpp.i

src/Core/SPK_Transformable.s: src/Core/SPK_Transformable.cpp.s
.PHONY : src/Core/SPK_Transformable.s

# target to generate assembly for a file
src/Core/SPK_Transformable.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Transformable.cpp.s
.PHONY : src/Core/SPK_Transformable.cpp.s

src/Core/SPK_Vector3D.obj: src/Core/SPK_Vector3D.cpp.obj
.PHONY : src/Core/SPK_Vector3D.obj

# target to build an object file
src/Core/SPK_Vector3D.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Vector3D.cpp.obj
.PHONY : src/Core/SPK_Vector3D.cpp.obj

src/Core/SPK_Vector3D.i: src/Core/SPK_Vector3D.cpp.i
.PHONY : src/Core/SPK_Vector3D.i

# target to preprocess a source file
src/Core/SPK_Vector3D.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Vector3D.cpp.i
.PHONY : src/Core/SPK_Vector3D.cpp.i

src/Core/SPK_Vector3D.s: src/Core/SPK_Vector3D.cpp.s
.PHONY : src/Core/SPK_Vector3D.s

# target to generate assembly for a file
src/Core/SPK_Vector3D.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Vector3D.cpp.s
.PHONY : src/Core/SPK_Vector3D.cpp.s

src/Core/SPK_Zone.obj: src/Core/SPK_Zone.cpp.obj
.PHONY : src/Core/SPK_Zone.obj

# target to build an object file
src/Core/SPK_Zone.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Zone.cpp.obj
.PHONY : src/Core/SPK_Zone.cpp.obj

src/Core/SPK_Zone.i: src/Core/SPK_Zone.cpp.i
.PHONY : src/Core/SPK_Zone.i

# target to preprocess a source file
src/Core/SPK_Zone.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Zone.cpp.i
.PHONY : src/Core/SPK_Zone.cpp.i

src/Core/SPK_Zone.s: src/Core/SPK_Zone.cpp.s
.PHONY : src/Core/SPK_Zone.s

# target to generate assembly for a file
src/Core/SPK_Zone.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Core/SPK_Zone.cpp.s
.PHONY : src/Core/SPK_Zone.cpp.s

src/Extensions/Emitters/SPK_NormalEmitter.obj: src/Extensions/Emitters/SPK_NormalEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.obj

# target to build an object file
src/Extensions/Emitters/SPK_NormalEmitter.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_NormalEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.cpp.obj

src/Extensions/Emitters/SPK_NormalEmitter.i: src/Extensions/Emitters/SPK_NormalEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.i

# target to preprocess a source file
src/Extensions/Emitters/SPK_NormalEmitter.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_NormalEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.cpp.i

src/Extensions/Emitters/SPK_NormalEmitter.s: src/Extensions/Emitters/SPK_NormalEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.s

# target to generate assembly for a file
src/Extensions/Emitters/SPK_NormalEmitter.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_NormalEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_NormalEmitter.cpp.s

src/Extensions/Emitters/SPK_RandomEmitter.obj: src/Extensions/Emitters/SPK_RandomEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.obj

# target to build an object file
src/Extensions/Emitters/SPK_RandomEmitter.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_RandomEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.cpp.obj

src/Extensions/Emitters/SPK_RandomEmitter.i: src/Extensions/Emitters/SPK_RandomEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.i

# target to preprocess a source file
src/Extensions/Emitters/SPK_RandomEmitter.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_RandomEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.cpp.i

src/Extensions/Emitters/SPK_RandomEmitter.s: src/Extensions/Emitters/SPK_RandomEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.s

# target to generate assembly for a file
src/Extensions/Emitters/SPK_RandomEmitter.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_RandomEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_RandomEmitter.cpp.s

src/Extensions/Emitters/SPK_SphericEmitter.obj: src/Extensions/Emitters/SPK_SphericEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.obj

# target to build an object file
src/Extensions/Emitters/SPK_SphericEmitter.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_SphericEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.cpp.obj

src/Extensions/Emitters/SPK_SphericEmitter.i: src/Extensions/Emitters/SPK_SphericEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.i

# target to preprocess a source file
src/Extensions/Emitters/SPK_SphericEmitter.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_SphericEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.cpp.i

src/Extensions/Emitters/SPK_SphericEmitter.s: src/Extensions/Emitters/SPK_SphericEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.s

# target to generate assembly for a file
src/Extensions/Emitters/SPK_SphericEmitter.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_SphericEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_SphericEmitter.cpp.s

src/Extensions/Emitters/SPK_StraightEmitter.obj: src/Extensions/Emitters/SPK_StraightEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.obj

# target to build an object file
src/Extensions/Emitters/SPK_StraightEmitter.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_StraightEmitter.cpp.obj
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.cpp.obj

src/Extensions/Emitters/SPK_StraightEmitter.i: src/Extensions/Emitters/SPK_StraightEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.i

# target to preprocess a source file
src/Extensions/Emitters/SPK_StraightEmitter.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_StraightEmitter.cpp.i
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.cpp.i

src/Extensions/Emitters/SPK_StraightEmitter.s: src/Extensions/Emitters/SPK_StraightEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.s

# target to generate assembly for a file
src/Extensions/Emitters/SPK_StraightEmitter.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Emitters/SPK_StraightEmitter.cpp.s
.PHONY : src/Extensions/Emitters/SPK_StraightEmitter.cpp.s

src/Extensions/Modifiers/SPK_Collision.obj: src/Extensions/Modifiers/SPK_Collision.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Collision.obj

# target to build an object file
src/Extensions/Modifiers/SPK_Collision.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Collision.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Collision.cpp.obj

src/Extensions/Modifiers/SPK_Collision.i: src/Extensions/Modifiers/SPK_Collision.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Collision.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_Collision.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Collision.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Collision.cpp.i

src/Extensions/Modifiers/SPK_Collision.s: src/Extensions/Modifiers/SPK_Collision.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Collision.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_Collision.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Collision.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Collision.cpp.s

src/Extensions/Modifiers/SPK_Destroyer.obj: src/Extensions/Modifiers/SPK_Destroyer.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.obj

# target to build an object file
src/Extensions/Modifiers/SPK_Destroyer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Destroyer.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.cpp.obj

src/Extensions/Modifiers/SPK_Destroyer.i: src/Extensions/Modifiers/SPK_Destroyer.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_Destroyer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Destroyer.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.cpp.i

src/Extensions/Modifiers/SPK_Destroyer.s: src/Extensions/Modifiers/SPK_Destroyer.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_Destroyer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Destroyer.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Destroyer.cpp.s

src/Extensions/Modifiers/SPK_LinearForce.obj: src/Extensions/Modifiers/SPK_LinearForce.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.obj

# target to build an object file
src/Extensions/Modifiers/SPK_LinearForce.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_LinearForce.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.cpp.obj

src/Extensions/Modifiers/SPK_LinearForce.i: src/Extensions/Modifiers/SPK_LinearForce.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_LinearForce.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_LinearForce.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.cpp.i

src/Extensions/Modifiers/SPK_LinearForce.s: src/Extensions/Modifiers/SPK_LinearForce.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_LinearForce.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_LinearForce.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_LinearForce.cpp.s

src/Extensions/Modifiers/SPK_ModifierGroup.obj: src/Extensions/Modifiers/SPK_ModifierGroup.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.obj

# target to build an object file
src/Extensions/Modifiers/SPK_ModifierGroup.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_ModifierGroup.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.cpp.obj

src/Extensions/Modifiers/SPK_ModifierGroup.i: src/Extensions/Modifiers/SPK_ModifierGroup.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_ModifierGroup.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_ModifierGroup.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.cpp.i

src/Extensions/Modifiers/SPK_ModifierGroup.s: src/Extensions/Modifiers/SPK_ModifierGroup.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_ModifierGroup.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_ModifierGroup.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_ModifierGroup.cpp.s

src/Extensions/Modifiers/SPK_Obstacle.obj: src/Extensions/Modifiers/SPK_Obstacle.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.obj

# target to build an object file
src/Extensions/Modifiers/SPK_Obstacle.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Obstacle.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.cpp.obj

src/Extensions/Modifiers/SPK_Obstacle.i: src/Extensions/Modifiers/SPK_Obstacle.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Obstacle.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.cpp.i

src/Extensions/Modifiers/SPK_Obstacle.s: src/Extensions/Modifiers/SPK_Obstacle.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Obstacle.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Obstacle.cpp.s

src/Extensions/Modifiers/SPK_PointMass.obj: src/Extensions/Modifiers/SPK_PointMass.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_PointMass.obj

# target to build an object file
src/Extensions/Modifiers/SPK_PointMass.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_PointMass.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_PointMass.cpp.obj

src/Extensions/Modifiers/SPK_PointMass.i: src/Extensions/Modifiers/SPK_PointMass.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_PointMass.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_PointMass.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_PointMass.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_PointMass.cpp.i

src/Extensions/Modifiers/SPK_PointMass.s: src/Extensions/Modifiers/SPK_PointMass.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_PointMass.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_PointMass.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_PointMass.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_PointMass.cpp.s

src/Extensions/Modifiers/SPK_Vortex.obj: src/Extensions/Modifiers/SPK_Vortex.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Vortex.obj

# target to build an object file
src/Extensions/Modifiers/SPK_Vortex.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Vortex.cpp.obj
.PHONY : src/Extensions/Modifiers/SPK_Vortex.cpp.obj

src/Extensions/Modifiers/SPK_Vortex.i: src/Extensions/Modifiers/SPK_Vortex.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Vortex.i

# target to preprocess a source file
src/Extensions/Modifiers/SPK_Vortex.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Vortex.cpp.i
.PHONY : src/Extensions/Modifiers/SPK_Vortex.cpp.i

src/Extensions/Modifiers/SPK_Vortex.s: src/Extensions/Modifiers/SPK_Vortex.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Vortex.s

# target to generate assembly for a file
src/Extensions/Modifiers/SPK_Vortex.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Modifiers/SPK_Vortex.cpp.s
.PHONY : src/Extensions/Modifiers/SPK_Vortex.cpp.s

src/Extensions/Renderers/SPK_Oriented3DRendererInterface.obj: src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.obj
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.obj

# target to build an object file
src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.obj
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.obj

src/Extensions/Renderers/SPK_Oriented3DRendererInterface.i: src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.i
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.i

# target to preprocess a source file
src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.i
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.i

src/Extensions/Renderers/SPK_Oriented3DRendererInterface.s: src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.s
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.s

# target to generate assembly for a file
src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.s
.PHONY : src/Extensions/Renderers/SPK_Oriented3DRendererInterface.cpp.s

src/Extensions/Renderers/SPK_QuadRendererInterface.obj: src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.obj
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.obj

# target to build an object file
src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.obj
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.obj

src/Extensions/Renderers/SPK_QuadRendererInterface.i: src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.i
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.i

# target to preprocess a source file
src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.i
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.i

src/Extensions/Renderers/SPK_QuadRendererInterface.s: src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.s
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.s

# target to generate assembly for a file
src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.s
.PHONY : src/Extensions/Renderers/SPK_QuadRendererInterface.cpp.s

src/Extensions/Zones/SPK_AABox.obj: src/Extensions/Zones/SPK_AABox.cpp.obj
.PHONY : src/Extensions/Zones/SPK_AABox.obj

# target to build an object file
src/Extensions/Zones/SPK_AABox.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_AABox.cpp.obj
.PHONY : src/Extensions/Zones/SPK_AABox.cpp.obj

src/Extensions/Zones/SPK_AABox.i: src/Extensions/Zones/SPK_AABox.cpp.i
.PHONY : src/Extensions/Zones/SPK_AABox.i

# target to preprocess a source file
src/Extensions/Zones/SPK_AABox.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_AABox.cpp.i
.PHONY : src/Extensions/Zones/SPK_AABox.cpp.i

src/Extensions/Zones/SPK_AABox.s: src/Extensions/Zones/SPK_AABox.cpp.s
.PHONY : src/Extensions/Zones/SPK_AABox.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_AABox.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_AABox.cpp.s
.PHONY : src/Extensions/Zones/SPK_AABox.cpp.s

src/Extensions/Zones/SPK_Cylinder.obj: src/Extensions/Zones/SPK_Cylinder.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Cylinder.obj

# target to build an object file
src/Extensions/Zones/SPK_Cylinder.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Cylinder.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Cylinder.cpp.obj

src/Extensions/Zones/SPK_Cylinder.i: src/Extensions/Zones/SPK_Cylinder.cpp.i
.PHONY : src/Extensions/Zones/SPK_Cylinder.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Cylinder.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Cylinder.cpp.i
.PHONY : src/Extensions/Zones/SPK_Cylinder.cpp.i

src/Extensions/Zones/SPK_Cylinder.s: src/Extensions/Zones/SPK_Cylinder.cpp.s
.PHONY : src/Extensions/Zones/SPK_Cylinder.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Cylinder.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Cylinder.cpp.s
.PHONY : src/Extensions/Zones/SPK_Cylinder.cpp.s

src/Extensions/Zones/SPK_Line.obj: src/Extensions/Zones/SPK_Line.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Line.obj

# target to build an object file
src/Extensions/Zones/SPK_Line.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Line.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Line.cpp.obj

src/Extensions/Zones/SPK_Line.i: src/Extensions/Zones/SPK_Line.cpp.i
.PHONY : src/Extensions/Zones/SPK_Line.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Line.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Line.cpp.i
.PHONY : src/Extensions/Zones/SPK_Line.cpp.i

src/Extensions/Zones/SPK_Line.s: src/Extensions/Zones/SPK_Line.cpp.s
.PHONY : src/Extensions/Zones/SPK_Line.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Line.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Line.cpp.s
.PHONY : src/Extensions/Zones/SPK_Line.cpp.s

src/Extensions/Zones/SPK_Plane.obj: src/Extensions/Zones/SPK_Plane.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Plane.obj

# target to build an object file
src/Extensions/Zones/SPK_Plane.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Plane.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Plane.cpp.obj

src/Extensions/Zones/SPK_Plane.i: src/Extensions/Zones/SPK_Plane.cpp.i
.PHONY : src/Extensions/Zones/SPK_Plane.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Plane.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Plane.cpp.i
.PHONY : src/Extensions/Zones/SPK_Plane.cpp.i

src/Extensions/Zones/SPK_Plane.s: src/Extensions/Zones/SPK_Plane.cpp.s
.PHONY : src/Extensions/Zones/SPK_Plane.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Plane.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Plane.cpp.s
.PHONY : src/Extensions/Zones/SPK_Plane.cpp.s

src/Extensions/Zones/SPK_Point.obj: src/Extensions/Zones/SPK_Point.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Point.obj

# target to build an object file
src/Extensions/Zones/SPK_Point.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Point.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Point.cpp.obj

src/Extensions/Zones/SPK_Point.i: src/Extensions/Zones/SPK_Point.cpp.i
.PHONY : src/Extensions/Zones/SPK_Point.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Point.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Point.cpp.i
.PHONY : src/Extensions/Zones/SPK_Point.cpp.i

src/Extensions/Zones/SPK_Point.s: src/Extensions/Zones/SPK_Point.cpp.s
.PHONY : src/Extensions/Zones/SPK_Point.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Point.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Point.cpp.s
.PHONY : src/Extensions/Zones/SPK_Point.cpp.s

src/Extensions/Zones/SPK_Ring.obj: src/Extensions/Zones/SPK_Ring.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Ring.obj

# target to build an object file
src/Extensions/Zones/SPK_Ring.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Ring.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Ring.cpp.obj

src/Extensions/Zones/SPK_Ring.i: src/Extensions/Zones/SPK_Ring.cpp.i
.PHONY : src/Extensions/Zones/SPK_Ring.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Ring.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Ring.cpp.i
.PHONY : src/Extensions/Zones/SPK_Ring.cpp.i

src/Extensions/Zones/SPK_Ring.s: src/Extensions/Zones/SPK_Ring.cpp.s
.PHONY : src/Extensions/Zones/SPK_Ring.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Ring.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Ring.cpp.s
.PHONY : src/Extensions/Zones/SPK_Ring.cpp.s

src/Extensions/Zones/SPK_Sphere.obj: src/Extensions/Zones/SPK_Sphere.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Sphere.obj

# target to build an object file
src/Extensions/Zones/SPK_Sphere.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Sphere.cpp.obj
.PHONY : src/Extensions/Zones/SPK_Sphere.cpp.obj

src/Extensions/Zones/SPK_Sphere.i: src/Extensions/Zones/SPK_Sphere.cpp.i
.PHONY : src/Extensions/Zones/SPK_Sphere.i

# target to preprocess a source file
src/Extensions/Zones/SPK_Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Sphere.cpp.i
.PHONY : src/Extensions/Zones/SPK_Sphere.cpp.i

src/Extensions/Zones/SPK_Sphere.s: src/Extensions/Zones/SPK_Sphere.cpp.s
.PHONY : src/Extensions/Zones/SPK_Sphere.s

# target to generate assembly for a file
src/Extensions/Zones/SPK_Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/Extensions/Zones/SPK_Sphere.cpp.s
.PHONY : src/Extensions/Zones/SPK_Sphere.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.obj: src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.i: src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.s: src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.obj: src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.i: src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.s: src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.obj: src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.i: src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.s: src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.obj: src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.i: src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.s: src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.obj: src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.i: src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.s: src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.cpp.s

src/RenderingAPIs/Irrlicht/SPK_IRRSystem.obj: src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.obj

# target to build an object file
src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.obj
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.obj

src/RenderingAPIs/Irrlicht/SPK_IRRSystem.i: src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.i

# target to preprocess a source file
src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.i
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.i

src/RenderingAPIs/Irrlicht/SPK_IRRSystem.s: src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.s

# target to generate assembly for a file
src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.s
.PHONY : src/RenderingAPIs/Irrlicht/SPK_IRRSystem.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLExtHandler.obj: src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLExtHandler.i: src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLExtHandler.s: src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLExtHandler.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.obj: src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.i: src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.s: src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.obj: src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.i: src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.s: src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.obj: src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.i: src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.s: src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.obj: src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.i: src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.s: src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.cpp.s

src/RenderingAPIs/OpenGL/SPK_GLRenderer.obj: src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.obj

# target to build an object file
src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.obj
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.obj

src/RenderingAPIs/OpenGL/SPK_GLRenderer.i: src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.i

# target to preprocess a source file
src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.i
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.i

src/RenderingAPIs/OpenGL/SPK_GLRenderer.s: src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.s

# target to generate assembly for a file
src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.s
.PHONY : src/RenderingAPIs/OpenGL/SPK_GLRenderer.cpp.s

src/SPK_All.obj: src/SPK_All.cpp.obj
.PHONY : src/SPK_All.obj

# target to build an object file
src/SPK_All.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_All.cpp.obj
.PHONY : src/SPK_All.cpp.obj

src/SPK_All.i: src/SPK_All.cpp.i
.PHONY : src/SPK_All.i

# target to preprocess a source file
src/SPK_All.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_All.cpp.i
.PHONY : src/SPK_All.cpp.i

src/SPK_All.s: src/SPK_All.cpp.s
.PHONY : src/SPK_All.s

# target to generate assembly for a file
src/SPK_All.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_All.cpp.s
.PHONY : src/SPK_All.cpp.s

src/SPK_GL_All.obj: src/SPK_GL_All.cpp.obj
.PHONY : src/SPK_GL_All.obj

# target to build an object file
src/SPK_GL_All.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_GL_All.cpp.obj
.PHONY : src/SPK_GL_All.cpp.obj

src/SPK_GL_All.i: src/SPK_GL_All.cpp.i
.PHONY : src/SPK_GL_All.i

# target to preprocess a source file
src/SPK_GL_All.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_GL_All.cpp.i
.PHONY : src/SPK_GL_All.cpp.i

src/SPK_GL_All.s: src/SPK_GL_All.cpp.s
.PHONY : src/SPK_GL_All.s

# target to generate assembly for a file
src/SPK_GL_All.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_GL_All.cpp.s
.PHONY : src/SPK_GL_All.cpp.s

src/SPK_IRR_ALL.obj: src/SPK_IRR_ALL.cpp.obj
.PHONY : src/SPK_IRR_ALL.obj

# target to build an object file
src/SPK_IRR_ALL.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_IRR_ALL.cpp.obj
.PHONY : src/SPK_IRR_ALL.cpp.obj

src/SPK_IRR_ALL.i: src/SPK_IRR_ALL.cpp.i
.PHONY : src/SPK_IRR_ALL.i

# target to preprocess a source file
src/SPK_IRR_ALL.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_IRR_ALL.cpp.i
.PHONY : src/SPK_IRR_ALL.cpp.i

src/SPK_IRR_ALL.s: src/SPK_IRR_ALL.cpp.s
.PHONY : src/SPK_IRR_ALL.s

# target to generate assembly for a file
src/SPK_IRR_ALL.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/SPK_IRR_ALL.cpp.s
.PHONY : src/SPK_IRR_ALL.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/metoritewars.dir/build.make CMakeFiles/metoritewars.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/metoritewars.dir/build.make CMakeFiles/metoritewars.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/metoritewars.dir/build.make CMakeFiles/metoritewars.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... base"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... metoritewars"
	@echo "... rebuild_cache"
	@echo "... src/Core/SPK_BufferHandler.obj"
	@echo "... src/Core/SPK_BufferHandler.i"
	@echo "... src/Core/SPK_BufferHandler.s"
	@echo "... src/Core/SPK_DEF.obj"
	@echo "... src/Core/SPK_DEF.i"
	@echo "... src/Core/SPK_DEF.s"
	@echo "... src/Core/SPK_Emitter.obj"
	@echo "... src/Core/SPK_Emitter.i"
	@echo "... src/Core/SPK_Emitter.s"
	@echo "... src/Core/SPK_Factory.obj"
	@echo "... src/Core/SPK_Factory.i"
	@echo "... src/Core/SPK_Factory.s"
	@echo "... src/Core/SPK_Group.obj"
	@echo "... src/Core/SPK_Group.i"
	@echo "... src/Core/SPK_Group.s"
	@echo "... src/Core/SPK_Interpolator.obj"
	@echo "... src/Core/SPK_Interpolator.i"
	@echo "... src/Core/SPK_Interpolator.s"
	@echo "... src/Core/SPK_Model.obj"
	@echo "... src/Core/SPK_Model.i"
	@echo "... src/Core/SPK_Model.s"
	@echo "... src/Core/SPK_Modifier.obj"
	@echo "... src/Core/SPK_Modifier.i"
	@echo "... src/Core/SPK_Modifier.s"
	@echo "... src/Core/SPK_Particle.obj"
	@echo "... src/Core/SPK_Particle.i"
	@echo "... src/Core/SPK_Particle.s"
	@echo "... src/Core/SPK_Registerable.obj"
	@echo "... src/Core/SPK_Registerable.i"
	@echo "... src/Core/SPK_Registerable.s"
	@echo "... src/Core/SPK_Renderer.obj"
	@echo "... src/Core/SPK_Renderer.i"
	@echo "... src/Core/SPK_Renderer.s"
	@echo "... src/Core/SPK_System.obj"
	@echo "... src/Core/SPK_System.i"
	@echo "... src/Core/SPK_System.s"
	@echo "... src/Core/SPK_Transformable.obj"
	@echo "... src/Core/SPK_Transformable.i"
	@echo "... src/Core/SPK_Transformable.s"
	@echo "... src/Core/SPK_Vector3D.obj"
	@echo "... src/Core/SPK_Vector3D.i"
	@echo "... src/Core/SPK_Vector3D.s"
	@echo "... src/Core/SPK_Zone.obj"
	@echo "... src/Core/SPK_Zone.i"
	@echo "... src/Core/SPK_Zone.s"
	@echo "... src/Extensions/Emitters/SPK_NormalEmitter.obj"
	@echo "... src/Extensions/Emitters/SPK_NormalEmitter.i"
	@echo "... src/Extensions/Emitters/SPK_NormalEmitter.s"
	@echo "... src/Extensions/Emitters/SPK_RandomEmitter.obj"
	@echo "... src/Extensions/Emitters/SPK_RandomEmitter.i"
	@echo "... src/Extensions/Emitters/SPK_RandomEmitter.s"
	@echo "... src/Extensions/Emitters/SPK_SphericEmitter.obj"
	@echo "... src/Extensions/Emitters/SPK_SphericEmitter.i"
	@echo "... src/Extensions/Emitters/SPK_SphericEmitter.s"
	@echo "... src/Extensions/Emitters/SPK_StraightEmitter.obj"
	@echo "... src/Extensions/Emitters/SPK_StraightEmitter.i"
	@echo "... src/Extensions/Emitters/SPK_StraightEmitter.s"
	@echo "... src/Extensions/Modifiers/SPK_Collision.obj"
	@echo "... src/Extensions/Modifiers/SPK_Collision.i"
	@echo "... src/Extensions/Modifiers/SPK_Collision.s"
	@echo "... src/Extensions/Modifiers/SPK_Destroyer.obj"
	@echo "... src/Extensions/Modifiers/SPK_Destroyer.i"
	@echo "... src/Extensions/Modifiers/SPK_Destroyer.s"
	@echo "... src/Extensions/Modifiers/SPK_LinearForce.obj"
	@echo "... src/Extensions/Modifiers/SPK_LinearForce.i"
	@echo "... src/Extensions/Modifiers/SPK_LinearForce.s"
	@echo "... src/Extensions/Modifiers/SPK_ModifierGroup.obj"
	@echo "... src/Extensions/Modifiers/SPK_ModifierGroup.i"
	@echo "... src/Extensions/Modifiers/SPK_ModifierGroup.s"
	@echo "... src/Extensions/Modifiers/SPK_Obstacle.obj"
	@echo "... src/Extensions/Modifiers/SPK_Obstacle.i"
	@echo "... src/Extensions/Modifiers/SPK_Obstacle.s"
	@echo "... src/Extensions/Modifiers/SPK_PointMass.obj"
	@echo "... src/Extensions/Modifiers/SPK_PointMass.i"
	@echo "... src/Extensions/Modifiers/SPK_PointMass.s"
	@echo "... src/Extensions/Modifiers/SPK_Vortex.obj"
	@echo "... src/Extensions/Modifiers/SPK_Vortex.i"
	@echo "... src/Extensions/Modifiers/SPK_Vortex.s"
	@echo "... src/Extensions/Renderers/SPK_Oriented3DRendererInterface.obj"
	@echo "... src/Extensions/Renderers/SPK_Oriented3DRendererInterface.i"
	@echo "... src/Extensions/Renderers/SPK_Oriented3DRendererInterface.s"
	@echo "... src/Extensions/Renderers/SPK_QuadRendererInterface.obj"
	@echo "... src/Extensions/Renderers/SPK_QuadRendererInterface.i"
	@echo "... src/Extensions/Renderers/SPK_QuadRendererInterface.s"
	@echo "... src/Extensions/Zones/SPK_AABox.obj"
	@echo "... src/Extensions/Zones/SPK_AABox.i"
	@echo "... src/Extensions/Zones/SPK_AABox.s"
	@echo "... src/Extensions/Zones/SPK_Cylinder.obj"
	@echo "... src/Extensions/Zones/SPK_Cylinder.i"
	@echo "... src/Extensions/Zones/SPK_Cylinder.s"
	@echo "... src/Extensions/Zones/SPK_Line.obj"
	@echo "... src/Extensions/Zones/SPK_Line.i"
	@echo "... src/Extensions/Zones/SPK_Line.s"
	@echo "... src/Extensions/Zones/SPK_Plane.obj"
	@echo "... src/Extensions/Zones/SPK_Plane.i"
	@echo "... src/Extensions/Zones/SPK_Plane.s"
	@echo "... src/Extensions/Zones/SPK_Point.obj"
	@echo "... src/Extensions/Zones/SPK_Point.i"
	@echo "... src/Extensions/Zones/SPK_Point.s"
	@echo "... src/Extensions/Zones/SPK_Ring.obj"
	@echo "... src/Extensions/Zones/SPK_Ring.i"
	@echo "... src/Extensions/Zones/SPK_Ring.s"
	@echo "... src/Extensions/Zones/SPK_Sphere.obj"
	@echo "... src/Extensions/Zones/SPK_Sphere.i"
	@echo "... src/Extensions/Zones/SPK_Sphere.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRBuffer.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRLineRenderer.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRPointRenderer.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRQuadRenderer.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRRenderer.s"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRSystem.obj"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRSystem.i"
	@echo "... src/RenderingAPIs/Irrlicht/SPK_IRRSystem.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLExtHandler.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLExtHandler.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLExtHandler.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineRenderer.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLLineTrailRenderer.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLPointRenderer.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLQuadRenderer.s"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLRenderer.obj"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLRenderer.i"
	@echo "... src/RenderingAPIs/OpenGL/SPK_GLRenderer.s"
	@echo "... src/SPK_All.obj"
	@echo "... src/SPK_All.i"
	@echo "... src/SPK_All.s"
	@echo "... src/SPK_GL_All.obj"
	@echo "... src/SPK_GL_All.i"
	@echo "... src/SPK_GL_All.s"
	@echo "... src/SPK_IRR_ALL.obj"
	@echo "... src/SPK_IRR_ALL.i"
	@echo "... src/SPK_IRR_ALL.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

